# Samsung Galaxy Note4
add_lunch_combo cmremix_trlteeur-userdebug
add_lunch_combo cmremix_trltetmo-userdebug
add_lunch_combo cmremix_trltespr-userdebug
add_lunch_combo cmremix_trlteusc-userdebug
add_lunch_combo cmremix_trltevzw-userdebug
# LG
add_lunch_combo cmremix_h850-userdebug
add_lunch_combo cmremix_h830-userdebug
add_lunch_combo cmremix_h918-userdebug
